on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install TexLive
      run: sudo apt-get install texlive-full
    - name: Build PDF
      run: cd tex && latexmk
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pdf
        path: tex/main.pdf
